<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE rss [
<!ELEMENT rss (channel)>
<!ELEMENT channel (title, link, atom:link, description, language, pubDate, lastBuildDate, docs, generator, item*)>
<!ELEMENT title (#PCDATA|span)*>
<!ELEMENT link (#PCDATA)>
<!ELEMENT atom:link EMPTY>
<!ELEMENT description ANY>
<!ELEMENT language (#PCDATA)>
<!ELEMENT pubDate (#PCDATA)>
<!ELEMENT lastBuildDate (#PCDATA)>
<!ELEMENT docs (#PCDATA)>
<!ELEMENT generator (#PCDATA)>
<!ELEMENT guid (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT a (#PCDATA|code)*>
<!ELEMENT code (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT p (#PCDATA|i|span|a)*>
<!ELEMENT span (#PCDATA)>
<!ELEMENT item (title, link, guid, pubDate, category+, description)>
<!ATTLIST rss version CDATA #REQUIRED xmlns:atom CDATA #REQUIRED>
<!ATTLIST atom:link href CDATA #REQUIRED rel CDATA #REQUIRED type CDATA #REQUIRED>
<!ATTLIST a href CDATA #REQUIRED>
<!ATTLIST i lang CDATA #IMPLIED>
<!ATTLIST span lang CDATA #IMPLIED>
]>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>iffalse</title>
        <link>https://bbguimaraes.com/blog</link>
        <atom:link href="https://bbguimaraes.com/blog/rss.xml" rel="self" type="application/rss+xml" />
        <description>assert("this should not be happening");</description>
        <language>en-us</language>
        <pubDate>Tue, 17 Dec 2024 13:14:16 +0000</pubDate>
        <lastBuildDate>Tue, 17 Dec 2024 13:14:16 +0000</lastBuildDate>
        <docs>http://www.rssboard.org/rss-specification</docs>
        <generator>vim</generator>
        <item>
            <title>Running away</title>
            <link>https://bbguimaraes.com/music/running-away.html</link>
            <guid>https://bbguimaraes.com/music/running-away.html</guid>
            <pubDate>Sat, 07 Sep 2024 16:12:09 GMT</pubDate>
            <category>music</category>
            <category>piano</category>
            <category>guitar</category>
            <category>bass</category>
            <category>short</category>
            <description><p>music piano guitar bass short</p><p>Joey Dosik</p><p>Continuing the theme of perfect love songs with a 70's feel and a deadly groove.</p></description>
        </item>
        <item>
            <title>How deep is your love</title>
            <link>https://bbguimaraes.com/music/how-deep-is-your-love.html</link>
            <guid>https://bbguimaraes.com/music/how-deep-is-your-love.html</guid>
            <pubDate>Sun, 11 Aug 2024 18:51:25 GMT</pubDate>
            <category>music</category>
            <category>guitar</category>
            <category>bass</category>
            <category>short</category>
            <description><p>music guitar bass short</p><p>Bee Gees</p><p>Some songs are just perfect, and this is one of them.</p></description>
        </item>
        <item>
            <title>Wayfaring stranger</title>
            <link>https://bbguimaraes.com/music/wayfaring-stranger.html</link>
            <guid>https://bbguimaraes.com/music/wayfaring-stranger.html</guid>
            <pubDate>Wed, 19 Jun 2024 13:15:39 GMT</pubDate>
            <category>music</category>
            <category>guitar</category>
            <category>vocals</category>
            <category>short</category>
            <description><p>music guitar vocals short</p></description>
        </item>
        <item>
            <title>~/places</title>
            <link>https://bbguimaraes.com/blog/places.html</link>
            <guid>https://bbguimaraes.com/blog/places.html</guid>
            <pubDate>Fri, 31 May 2024 06:52:00 GMT</pubDate>
            <category>blog</category>
            <description><p>You might have noticed I like to travel.  For a long time, it did not appeal to me to share this aspect of my life, as it is far from being an uncommon interest, especially in the era of vain social media pretension and ostentation, and no end of people traveling to supposedly “find themselves”, but who, in the words of one of the great Roman poets, <span lang="la">“caelum, nón animum mútant, quí tráns mare currunt”</span>.</p><p>But that has gradually changed over the past few years, to the point that I have now, after a week of furious programming, added a new <a href="https://bbguimaraes.com/places">section</a> to this web site dedicated to it.  Read on for an explanation, jump to the <a href="https://bbguimaraes.com/blog/places.html#conclusion">conclusion</a> if you do not like to read (but then this is probably not the place for you in the first place…), or just go directly there and explore.</p></description>
        </item>
        <item>
            <title>Via Francigena</title>
            <link>https://bbguimaraes.com/places/via-francigena.html</link>
            <guid>https://bbguimaraes.com/places/via-francigena.html</guid>
            <pubDate>Thu, 29 Feb 2024 00:00:01 GMT</pubDate>
            <category>place</category>
            <description>One of the two major early-Mediaeval peregrination routes across Western Europe — the other being, of course, the famous Camino de Santiago, which it predates by a few centuries and to which it is roughly perpendicular.  Beginning in Canterbury (specifically, Canterbury Cathedral, seat of the Archbishop of the Church of England), at the southeastern corner of Britain near the Thames estuary, it crosses France, Switzerland, and the entirety of the Italian peninsula, passing through Rome and ending in Santa Maria di Leuca in Puglia, the southeastern end of Italy, after more than three thousand kilometers.  From there pilgrims would sail across the Mediterranean to the Holy Land.  Thus it connects, together with Camino de Santiago, Compostela, Canterbury, Rome, and Jerusalem, the main peregrination sites of Christianity.</description>
        </item>
        <item>
            <title>Formia</title>
            <link>https://bbguimaraes.com/places/formia.html</link>
            <guid>https://bbguimaraes.com/places/formia.html</guid>
            <pubDate>Thu, 29 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>As many of the cities along the Tyrrhenian coast on the ancient via Appia, Formia was a favored place for Roman seaside villae — including one belonging to the stepfather of the emperor Augustus.  Its Greek name <span lang="grc">Όρμιαι</span> (<span lang="la">Hormiae</span> in Latin, from a word for “harbor”) refers to its many ports and the mild maritime climate provided by its surroundings: the gulf of Gaeta and the monti Aurunci.  The remains of many of these villae and ports can still be seen all they from the city center to the rocky shore on the way to <a href="https://www.openstreetmap.org/node/8390626221">monte Scauri</a>, with salient pieces of two-thousand-year-old mosaics coming out of the rock every now and then.</description>
        </item>
        <item>
            <title>Minturno</title>
            <link>https://bbguimaraes.com/places/minturno.html</link>
            <guid>https://bbguimaraes.com/places/minturno.html</guid>
            <pubDate>Wed, 28 Feb 2024 00:00:01 GMT</pubDate>
            <category>place</category>
            <description>The Roman city of Minturnae, in the southern region of Lazio, was built in 312 B.C. on the site of the previous conquered ancient city of the same name, part of the Pentapoli Aurunca.  Its location, protected by the monti Aurunci to the north, golfo di Gaeta and mar Tirreno to the southwest, and the river Liris (now called Garigliano) to the southeast, and right on via Appia, the “regina viarum” (queen of roads, the main road connecting Rome to the southern end of the peninsula), made it a strategic point for a colony.</description>
        </item>
        <item>
            <title>Cappella Sansevero</title>
            <link>https://bbguimaraes.com/places/sansevero.html</link>
            <guid>https://bbguimaraes.com/places/sansevero.html</guid>
            <pubDate>Wed, 28 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>This post will be different than usual.  Taking photographs is forbidden inside the cappella, so these are not mine, but taken from their web site (I hope they will not sue me for the mountains of money I make with each post).</description>
        </item>
        <item>
            <title>Ischia</title>
            <link>https://bbguimaraes.com/places/ischia.html</link>
            <guid>https://bbguimaraes.com/places/ischia.html</guid>
            <pubDate>Tue, 27 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>The last stop of my marathon in the Gulf of Napoli.  I had become so enamored of the island from watching it all the way across the Gulf of Gaeta, more than 60km away — it is located right between the two gulfs, in the area where Campi Flegrei, the huge volcanic caldera, enters the Mediterranean sea, forming Penisola flegrea and the surrounding islands — seeing its dim figure through the maritime mist, its shaded contour against the colored sky at sunset, its dark green suspended in the bright blue where both sky and sea meet on sunny days (<a href="https://bbguimaraes.com/places/coreno-ausonio.html">see</a> <a href="https://bbguimaraes.com/places/castelforte.html">the</a> <a href="https://bbguimaraes.com/places/santi-cosma-e-damiano.html">other</a> <a href="https://bbguimaraes.com/places/gaeta.html">posts</a> <a href="https://bbguimaraes.com/places/napoli.html">where</a> <a href="https://bbguimaraes.com/places/capri.html">it</a> <a href="https://bbguimaraes.com/places/monte-solaro.html">makes</a> <a href="https://bbguimaraes.com/places/sorrento.html">an</a> <a href="https://bbguimaraes.com/places/herculaneum.html">appearance</a>), that I could not leave Campania without going there.</description>
        </item>
        <item>
            <title>Pompeii</title>
            <link>https://bbguimaraes.com/places/pompeii.html</link>
            <guid>https://bbguimaraes.com/places/pompeii.html</guid>
            <pubDate>Mon, 26 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>If you are obsessed with Ancient Rome as I am (as I hope you are), you knew this was coming.  After the Palatine hill in Rome itself, the most famous Roman ruins which survive to this day are certainly the city of Pompeii.  As its neighbor <a href="https://bbguimaraes.com/places/herculaneum.html">Herculaneum</a>, it was at the time at the seaside (built on top of a layer of lava from a previous eruption), it was buried under several meters of volcanic material expelled from <a href="https://bbguimaraes.com/places/vesuvius.html">mount Vesuvius</a> in 79 AD, remained lost for more than a millennium and a half until it was accidentally rediscovered, and now provides an unbelievable view into what life was like in the Roman empire two thousand years ago.</description>
        </item>
        <item>
            <title>Herculaneum</title>
            <link>https://bbguimaraes.com/places/herculaneum.html</link>
            <guid>https://bbguimaraes.com/places/herculaneum.html</guid>
            <pubDate>Sun, 25 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>At the foot of <a href="https://bbguimaraes.com/places/vesuvius.html">mount Vesuvius</a> there existed, until the fated year of 79 AD, a Roman town named <i>Herculaneum</i>.  Legend says it was founded by the Greek hero <span lang="grc">Ἡρακλῆς</span> (Heracles, known to the Romans as Hercules) himself while returning from Iberia after one of his twelve labors, and named after him.  While not as large as the nearby city of <a href="https://bbguimaraes.com/places/pompeii.html">Pompeii</a>, its position at (what was then) the seaside made it a retreat for Roman nobility including, it is believed, Julius Caesar's father-in-law, Lucius Calpurnius Piso Caesonius, and its four thousand inhabitants enjoyed decent prosperity.</description>
        </item>
        <item>
            <title>Something (guitar solo)</title>
            <link>https://bbguimaraes.com/music/something-solo.html</link>
            <guid>https://bbguimaraes.com/music/something-solo.html</guid>
            <pubDate>Tue, 13 Feb 2024 00:34:46 GMT</pubDate>
            <category>music</category>
            <category>guitar</category>
            <category>bass</category>
            <category>short</category>
            <description><p>music guitar bass short</p><p>The Beatles</p></description>
        </item>
        <item>
            <title>Suio</title>
            <link>https://bbguimaraes.com/places/suio.html</link>
            <guid>https://bbguimaraes.com/places/suio.html</guid>
            <pubDate>Fri, 09 Feb 2024 00:00:01 GMT</pubDate>
            <category>place</category>
            <description>Suio, on the border between the Italian regions of Lazio and Campania, is situated in an area rich in thermal waters, considered some of the best in Italy for the presence of iodine and therapeutical for their richness of sulphur.</description>
        </item>
        <item>
            <title>Fonte di Salomone, Sant'Andrea del Garigliano</title>
            <link>https://bbguimaraes.com/places/salomone.html</link>
            <guid>https://bbguimaraes.com/places/salomone.html</guid>
            <pubDate>Fri, 09 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>After crossing via Valle di Suio, next to the road which follows the Garigliano river, in the comune of Sant'Andrea del Garigliano, almost in Frosinone, just before the end of the province of Latina, there is a magical place, hidden among the trees that surround the river margins.</description>
        </item>
        <item>
            <title>Sorrento</title>
            <link>https://bbguimaraes.com/places/sorrento.html</link>
            <guid>https://bbguimaraes.com/places/sorrento.html</guid>
            <pubDate>Tue, 06 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Known to the Romans as Surrentum, from Greek Συρρεντόν, meaning “a confluence”, from the verb “συρρέω”.  A city protected by steep rock walls, with a single entrance where parts of the Greek walls and gate can still be seen, and by the waters of the gulf of Napoli.  I spent most of my time there (just over a day, unfortunately) walking Capo di Sorrento, and most of that in Bagni della Regina Giovanna, amazing Roman ruins from the 1st century AD, with its own natural swimming pool and port.</description>
        </item>
        <item>
            <title>Monte Tuoro, Capri</title>
            <link>https://bbguimaraes.com/places/monte-tuoro.html</link>
            <guid>https://bbguimaraes.com/places/monte-tuoro.html</guid>
            <pubDate>Mon, 05 Feb 2024 00:00:02 GMT</pubDate>
            <category>place</category>
            <description>Last set from Capri, though I would post every single picture if I could.  These are taken over the two days I spent there, along two sentieri: one going from the famous Faraglioni up to monte Tuoro, the other crossing the entire Western coast passing through the ruins of Roman forts and rocky paths along the limestone cliffs, where dolphins and whales can be regularly seen (a pity they were too far away to get a good picture or video of them).</description>
        </item>
        <item>
            <title>Belvedere filosofico, Capri</title>
            <link>https://bbguimaraes.com/places/belvedere-filosofico.html</link>
            <guid>https://bbguimaraes.com/places/belvedere-filosofico.html</guid>
            <pubDate>Mon, 05 Feb 2024 00:00:01 GMT</pubDate>
            <category>place</category>
            <description>Faith, in one sentence.</description>
        </item>
        <item>
            <title>Monte Solaro, Capri</title>
            <link>https://bbguimaraes.com/places/monte-solaro.html</link>
            <guid>https://bbguimaraes.com/places/monte-solaro.html</guid>
            <pubDate>Mon, 05 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Climbing monte Solaro in the island of Capri.  The path begins in Porto di Marina Grande, right after leaving the boat.  It goes up through tiny streets and stairs along the Northern portion of the town of Capri, then begins an almost vertical ascent through Scala Fenicia, a stairway built on the face of the mount in the 7th century B.C. by the Greek colonizers of the island (there are no pictures at this point because I was busy trying to survive the almost 1000 steps).</description>
        </item>
        <item>
            <title>Capri</title>
            <link>https://bbguimaraes.com/places/capri.html</link>
            <guid>https://bbguimaraes.com/places/capri.html</guid>
            <pubDate>Sat, 03 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>I've been to many beautiful places in my life.  But none compares, at least in terms of pure natural beauty, to this piccola isola at the Southern end of the gulf of Napoli, a few kilometers away from the Sorrento peninsula.</description>
        </item>
        <item>
            <title>Pompei</title>
            <link>https://bbguimaraes.com/places/pompei.html</link>
            <guid>https://bbguimaraes.com/places/pompei.html</guid>
            <pubDate>Fri, 02 Feb 2024 00:00:01 GMT</pubDate>
            <category>place</category>
            <description>I was in Pompei very briefly — just a single day, on the way to and from Vesuvius.  That was much less than the four years I estimate it will take me to visit its famous ruins, given that my mind lives more in the Roman empire than in whatever this “real” life is, next time I'm there.</description>
        </item>
        <item>
            <title>Vesuvius</title>
            <link>https://bbguimaraes.com/places/vesuvius.html</link>
            <guid>https://bbguimaraes.com/places/vesuvius.html</guid>
            <pubDate>Fri, 02 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Vesuvius rises 1281m on the coast of the gulf of Napoli.  In 79 AD it destroyed, in one of the most catastrophic eruptions in recorded history, many surrounding Roman cities.  Up to 1.5t of material were expelled per second, in clouds 33km high, releasing 100,000 times the energy of the 1945 atomic bombings.  The mountains surrounding the caldera are the remnants of the original, much higher (2km) Monte Somma, destroyed by that eruption.</description>
        </item>
        <item>
            <title>Napoli</title>
            <link>https://bbguimaraes.com/places/napoli.html</link>
            <guid>https://bbguimaraes.com/places/napoli.html</guid>
            <pubDate>Thu, 01 Feb 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>The Greek warrior Ὀδυσσεύς/Odysseús/Ulysses sails the Tyrrhenian Sea in his journey returning from the Trojan War.  He passes the Italian coast by the island of the Sirens, beautiful female sea creatures who lure men to their death with their voices and music.  With counsel from the goddess and sorcerer Circe, he is able to escape the enchantment, and proceeds his travels, through the underworld of ᾍδης/Hades.</description>
        </item>
        <item>
            <title>Gaeta</title>
            <link>https://bbguimaraes.com/places/gaeta.html</link>
            <guid>https://bbguimaraes.com/places/gaeta.html</guid>
            <pubDate>Wed, 31 Jan 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Gaeta, a coastal city in the Riviera d'Ulisse, in the Southern end of Lazio, built on the tip of Torre di Orlando, a promontory formed at the feet of the Monti Aurunci.  Aeneas, in Virgil's Aeneid, buries his wet-nurse, Καιήτη, in this place while sailing the Lazio, giving the city its name.</description>
        </item>
        <item>
            <title>Santi Cosma e Damiano</title>
            <link>https://bbguimaraes.com/places/santi-cosma-e-damiano.html</link>
            <guid>https://bbguimaraes.com/places/santi-cosma-e-damiano.html</guid>
            <pubDate>Mon, 29 Jan 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>The equally small comune of Santi Cosma e Damiano is situated right next to <a href="https://bbguimaraes.com/places/castelforte.html">Castelforte</a>, on the same hillside overlooking the Garigliano valley and the gulf of <a href="https://bbguimaraes.com/places/gaeta.html">Gaeta</a> (but don't mix the two towns, or you'll upset the locals on both sides).  There is a stony road which climbs almost to the top of the hill, the highest point in the surrounding area, the village of <a href="https://www.openstreetmap.org/node/1235709903">Ventosa</a> and its 12th-century Romanesque watch tower, with a view of not only the valley and the vastness of the gulf, but stretching all the way to monte Cairo in the north, monti Aurunci in the west, Roccamonfina to the east, and going as far as <a href="vesuvius.html">Vesuvius</a> and the island of Ischia in the south-east when the weather is sufficiently clear.</description>
        </item>
        <item>
            <title>Minturnae, Minturno</title>
            <link>https://bbguimaraes.com/places/minturnae.html</link>
            <guid>https://bbguimaraes.com/places/minturnae.html</guid>
            <pubDate>Sat, 27 Jan 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Minturnae was one of the major ancient city of the Αὔσονες/Auruncí, who inhabited the mountainous regions near the Gulf of Gaeta.  It was conquered by Rome in 314 B.C and completely destroyed, but later reconstructed as a Roman settlement and frequented by the nobility, as were the other villae maritimae on the Tyrrhenian coast: Formiae, Pirae, and Cáiéta.</description>
        </item>
        <item>
            <title>Castelforte</title>
            <link>https://bbguimaraes.com/places/castelforte.html</link>
            <guid>https://bbguimaraes.com/places/castelforte.html</guid>
            <pubDate>Wed, 24 Jan 2024 00:00:01 GMT</pubDate>
            <category>place</category>
            <description>Castelforte is a small comune in the Garigliano valley.  It is where Suio (see previous post) is contained and together with it, as the name suggests, served as a protective and vigilant center for the entire valley, from the surrounding mountains down to the delta of the river in the gulf of Gaeta.</description>
        </item>
        <item>
            <title>Coreno Ausonio</title>
            <link>https://bbguimaraes.com/places/coreno-ausonio.html</link>
            <guid>https://bbguimaraes.com/places/coreno-ausonio.html</guid>
            <pubDate>Wed, 24 Jan 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>A trail up the Garigliano valley towards the oriental Aurunci mountains — an area at the border between Lazio and Campania populated since pre-Roman times due to its marble, limestone, and thermal waters — and a sunset in the gulf of Gaeta in the Tyrrhenian sea.</description>
        </item>
        <item>
            <title>Porto Alegre</title>
            <link>https://bbguimaraes.com/places/porto-alegre.html</link>
            <guid>https://bbguimaraes.com/places/porto-alegre.html</guid>
            <pubDate>Sat, 20 Jan 2024 00:00:00 GMT</pubDate>
            <category>place</category>
            <description />
        </item>
        <item>
            <title>Tennessee whiskey</title>
            <link>https://bbguimaraes.com/music/tennessee-whiskey.html</link>
            <guid>https://bbguimaraes.com/music/tennessee-whiskey.html</guid>
            <pubDate>Sat, 23 Dec 2023 17:24:54 GMT</pubDate>
            <category>music</category>
            <category>guitar</category>
            <category>bass</category>
            <category>short</category>
            <description><p>music guitar bass short</p><p>Dean Dillon, Linda Hargrove</p></description>
        </item>
        <item>
            <title>Arroio do Sal</title>
            <link>https://bbguimaraes.com/places/arroio-do-sal.html</link>
            <guid>https://bbguimaraes.com/places/arroio-do-sal.html</guid>
            <pubDate>Fri, 22 Dec 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Happy summer (or winter) solstice.</description>
        </item>
        <item>
            <title>São Luiz da Terceira Légua</title>
            <link>https://bbguimaraes.com/places/terceira-legua.html</link>
            <guid>https://bbguimaraes.com/places/terceira-legua.html</guid>
            <pubDate>Tue, 05 Dec 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description />
        </item>
        <item>
            <title>Istanbul</title>
            <link>https://bbguimaraes.com/places/istanbul.html</link>
            <guid>https://bbguimaraes.com/places/istanbul.html</guid>
            <pubDate>Fri, 24 Nov 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Βυζάντιον / Κωνσταντινούπολη / εἰς τὴν Πόλιν.  Thousands of years of history, a mixture of Greek, Roman, Ottoman, Western and Eastern cultures, and marvelous places, natural and man-made.  I hope to return here someday for a longer stay.  (I can now also claim to have officially been to Asia)</description>
        </item>
        <item>
            <title>Mediterranean sea</title>
            <link>https://bbguimaraes.com/places/mediterranean.html</link>
            <guid>https://bbguimaraes.com/places/mediterranean.html</guid>
            <pubDate>Mon, 23 Oct 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>While putting together the <a href="https://bbguimaraes.com/places/">page</a> from the last post this past week and going through my photograph archive, I was caught yet again by these ones and put it on my list to share them, since they are some of my favorites among all the pictures I've ever taken.</description>
        </item>
        <item>
            <title>Villa Reale, Milano</title>
            <link>https://bbguimaraes.com/places/villa_reale.html</link>
            <guid>https://bbguimaraes.com/places/villa_reale.html</guid>
            <pubDate>Fri, 20 Oct 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>How can you not love a place where you can walk into a public garden and find a temple to the Greek Fates and passages from Aeneas' journey through Hades from Virgil's Aeneid?</description>
        </item>
        <item>
            <title>Torino</title>
            <link>https://bbguimaraes.com/places/torino.html</link>
            <guid>https://bbguimaraes.com/places/torino.html</guid>
            <pubDate>Tue, 17 Oct 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>(a bit unexpected to post again, but Italy is just a fantastic place)</description>
        </item>
        <item>
            <title>Trento, Padova, Bologna</title>
            <link>https://bbguimaraes.com/places/trento.html</link>
            <guid>https://bbguimaraes.com/places/trento.html</guid>
            <pubDate>Mon, 16 Oct 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Magnifica Trento, sotto le Alpi. With a few bonus photographs from Padova and Bologna.</description>
        </item>
        <item>
            <title>Trieste</title>
            <link>https://bbguimaraes.com/places/trieste.html</link>
            <guid>https://bbguimaraes.com/places/trieste.html</guid>
            <pubDate>Tue, 10 Oct 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>A nubilous but spectacular walk along the Adriatic coast.  Trieste / Opicina / Prosecco / Miramare / Barcola</description>
        </item>
        <item>
            <title>Venezia</title>
            <link>https://bbguimaraes.com/places/venezia.html</link>
            <guid>https://bbguimaraes.com/places/venezia.html</guid>
            <pubDate>Fri, 06 Oct 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Always a delight to revisit the Repubblica Marinara and see how it's fared since the fall of the Byzantine Empire.</description>
        </item>
        <item>
            <title>Praha</title>
            <link>https://bbguimaraes.com/places/prague.html</link>
            <guid>https://bbguimaraes.com/places/prague.html</guid>
            <pubDate>Mon, 02 Oct 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description>Parting with a dear old friend is always painful, but sometimes inevitable.</description>
        </item>
        <item>
            <title>Brno</title>
            <link>https://bbguimaraes.com/places/brno.html</link>
            <guid>https://bbguimaraes.com/places/brno.html</guid>
            <pubDate>Fri, 29 Sep 2023 00:00:00 GMT</pubDate>
            <category>place</category>
            <description />
        </item>
        <item>
            <title>The power of the powerless</title>
            <link>https://bbguimaraes.com/lib/the-power-of-the-powerless.html</link>
            <guid>https://bbguimaraes.com/lib/the-power-of-the-powerless.html</guid>
            <pubDate>Mon, 11 Sep 2023 15:06:07 GMT</pubDate>
            <category>books</category>