<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE rss [
<!ELEMENT rss (channel)>
<!ELEMENT channel (title, link, atom:link, description, language, pubDate, lastBuildDate, docs, generator, item*)>
<!ELEMENT title (#PCDATA|span)*>
<!ELEMENT link (#PCDATA)>
<!ELEMENT atom:link EMPTY>
<!ELEMENT description ANY>
<!ELEMENT language (#PCDATA)>
<!ELEMENT pubDate (#PCDATA)>
<!ELEMENT lastBuildDate (#PCDATA)>
<!ELEMENT docs (#PCDATA)>
<!ELEMENT generator (#PCDATA)>
<!ELEMENT guid (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT a (#PCDATA|code)*>
<!ELEMENT code (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT p (#PCDATA|i|span)*>
<!ELEMENT span (#PCDATA)>
<!ELEMENT item (title, link, guid, pubDate, category+, description)>
<!ATTLIST rss version CDATA #REQUIRED xmlns:atom CDATA #REQUIRED>
<!ATTLIST atom:link href CDATA #REQUIRED rel CDATA #REQUIRED type CDATA #REQUIRED>
<!ATTLIST a href CDATA #REQUIRED>
<!ATTLIST i lang CDATA #IMPLIED>
<!ATTLIST span lang CDATA #IMPLIED>
]>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>iffalse</title>
        <link>https://bbguimaraes.com/blog</link>
        <atom:link href="https://bbguimaraes.com/blog/rss.xml" rel="self" type="application/rss+xml" />
        <description>assert("this should not be happening");</description>
        <language>en-us</language>
        <pubDate>Wed, 26 Jul 2023 19:34:49 GMT</pubDate>
        <lastBuildDate>Wed, 26 Jul 2023 19:34:49 GMT</lastBuildDate>
        <docs>http://www.rssboard.org/rss-specification</docs>
        <generator>vim</generator>
        <item>
            <title>Pride and prejudice</title>
            <link>https://bbguimaraes.com/lib/pride-and-prejudice.html</link>
            <guid>https://bbguimaraes.com/lib/pride-and-prejudice.html</guid>
            <pubDate>Wed, 26 Jul 2023 19:34:49 GMT</pubDate>
            <category>books</category>
            <description><p>Pride and prejudice, Jane Austen</p><p>While it is on the surface a romance, this alone would not account for the immense popularity of this book.  As its initial title, <i>First Impressions</i>, suggests, there is much more to it than a simple love story. It is at its core about the <i>philosophy</i> of love but, as a novelist, Austen's exploration of the theme is that of a painter or a poet: not formal but abstract, deeper and more captivating, expressing what can be felt but not easily rationalized.</p></description>
        </item>
        <item>
            <title><span lang="grc">Ἀπολογία Σωκράτους</span> (Apology of Socrates)</title>
            <link>https://bbguimaraes.com/lib/apologia.html</link>
            <guid>https://bbguimaraes.com/lib/apologia.html</guid>
            <pubDate>Wed, 12 Jul 2023 18:04:19 GMT</pubDate>
            <category>books</category>
            <description><p><span lang="grc">Ἀπολογία Σωκράτους</span> (Apology of Socrates), Plato</p><p>One of the Platonic dialogues which depicts the last days of Socrates (together with <i>Euthyphro</i>, <i>Crito</i>, <i>Phaedo</i>, and Xenophon's <i>Apology</i>).  Having been accused of "corrupting the youth" and teaching men "not to receive the gods whom the city receives", and knowing what his fate is, the philosopher consults his δαιμόνιον (<i lang="grc">daimonion</i>, his "divine faculty") and decides that, rather than desisting and escaping from his trial, as his prosecutors would have him do, he is to deliver his defense in front of the court and face the ultimate consequence.</p></description>
        </item>
        <item>
            <title>Brave new world</title>
            <link>https://bbguimaraes.com/lib/brave-new-world.html</link>
            <guid>https://bbguimaraes.com/lib/brave-new-world.html</guid>
            <pubDate>Sun, 22 Jan 2023 22:26:22 GMT</pubDate>
            <category>books</category>
            <description><p>Brave new world, Aldous Leonard Huxley</p><p>The World State in the Year of Our Ford 632 is perfectly constructed: humans are produced in laboratories, engineered and conditioned for their societal purpose, kept young until their death, with free access to drugs and all sorts of technological amenities.  Women are infertile or expertly trained in contraceptive rituals, encouraged to have as many partners as possible, and, if they ever "feel out of sorts", administered a <i>passion surrogate</i> or <i>pregnancy substitute</i>.</p></description>
        </item>
        <item>
            <title><span lang="grc">Τὰ εἰς ἑαυτόν</span> (Meditations)</title>
            <link>https://bbguimaraes.com/lib/meditations.html</link>
            <guid>https://bbguimaraes.com/lib/meditations.html</guid>
            <pubDate>Sun, 01 Jan 2023 12:21:23 GMT</pubDate>
            <category>books</category>
            <description><p><span lang="grc">Τὰ εἰς ἑαυτόν</span> (Meditations), Marcus Aurelius Antoninus Augustus</p><p>A book which should be mandatory reading for every man entering adult life. With deep roots in classical Greek and early Christian philosophy, these notes by Marcus Aurelius (the last of the "Good Emperors", maintainers of the Pax Romana in the first two centuries A.D.), written in the last third of his life, describe his conception of masculine virtue.</p></description>
        </item>
        <item>
            <title>Booklet printing with LaTeX</title>
            <link>https://bbguimaraes.com/blog/booklet-printing-with-latex.html</link>
            <guid>https://bbguimaraes.com/blog/booklet-printing-with-latex.html</guid>
            <pubDate>Sat, 17 Dec 2022 17:49:01 GMT</pubDate>
            <category>books</category>
            <category>latex</category>
            <category>linux</category>
            <category>unix</category>
            <description>In another episode of "there was something very peculiar I wanted to do, there existed no decent guides on the internet, so here is mine": booklet printing.  I had the need to turn a LaTeX document I had produced into something physical which could be taken with me easily.  After a few days of research and experimentation and some wasted paper, I arrived at a very satisfying result.  There is something about real-life printed books (even a small one) which cannot be translated to digital media.  So here is how you can do the same for any PDF document you might have.</description>
        </item>
        <item>
            <title>strace prelude in C</title>
            <link>https://bbguimaraes.com/blog/strace-prelude-in-c.html</link>
            <guid>https://bbguimaraes.com/blog/strace-prelude-in-c.html</guid>
            <pubDate>Sun, 17 Apr 2022 10:34:57 GMT</pubDate>
            <category>assembly</category>
            <category>c</category>
            <category>debugging</category>
            <category>linux</category>
            <category>man</category>
            <category>programming</category>
            <category>strace</category>
            <category>unix</category>
            <description>Much has been written about the venerable <a href="https://strace.io/"><code>strace</code></a>, one of the most important allies of the systems programmer.  However, the focus is often on the specifics of the particular program being examined, not on the functioning of <code>strace</code> itself and the operating system environment involved in the execution of the process.  Today we explore this neglected part of the system call trace.</description>
        </item>
        <item>
            <title>C++ virtual tables</title>
            <link>https://bbguimaraes.com/blog/c++-virtual-tables.html</link>
            <guid>https://bbguimaraes.com/blog/c++-virtual-tables.html</guid>
            <pubDate>Tue, 22 Feb 2022 20:09:10 GMT</pubDate>
            <category>assembly</category>
            <category>c</category>
            <category>c++</category>
            <category>linux</category>
            <category>programming</category>
            <category>unix</category>
            <description>One of the principal differences between C and C++ is the latter's direct support for virtual functions.  While it is entirely possible, as will be demonstrated, to implement virtual dispatch in C, C++ offers language primitives that instruct the compiler to generate the necessary back end code automatically.</description>
        </item>
        <item>
            <title>nngn - lua &amp; wasm</title>
            <link>https://bbguimaraes.com/blog/nngn-lua-wasm.html</link>
            <guid>https://bbguimaraes.com/blog/nngn-lua-wasm.html</guid>
            <pubDate>Tue, 23 Mar 2021 10:10:25 GMT</pubDate>
            <category>c</category>
            <category>lua</category>
            <category>nngn</category>
            <category>programming</category>
            <category>wasm</category>
            <description>This is a short interlude in my series of posts.  The original post in the series <a href="https://bbguimaraes.com/blog/nngn.html#ubi">briefly mentioned</a> that one of my build targets is WebAssembly, and the <a href="https://bbguimaraes.com/blog/nngn-lua.html">last one</a> was all about how Lua is a fundamental piece of the architecture.  How that build process works did not seem particularly interesting, so I did not write about it.</description>
        </item>
        <item>
            <title>nngn - lua</title>
            <link>https://bbguimaraes.com/blog/nngn-lua.html</link>
            <guid>https://bbguimaraes.com/blog/nngn-lua.html</guid>
            <pubDate>Sun, 30 Aug 2020 17:54:09 GMT</pubDate>
            <category>lua</category>
            <category>netcat</category>
            <category>nngn</category>
            <category>programming</category>
            <category>readline</category>
            <category>socket</category>
            <category>unix</category>
            <category>vim</category>
            <description>Out of sheer patriotic duty, the main component of the engine is <a href="https://www.lua.org">Lua</a>.  The famous tiny scripting language is the only hard dependency (other than a C++ compiler and a vaguely POSIX-compliant operating system) and is the interstitial fluid that coordinates all the other components.</description>
        </item>
        <item>
            <title>nngn</title>
            <link>https://bbguimaraes.com/blog/nngn.html</link>
            <guid>https://bbguimaraes.com/blog/nngn.html</guid>
            <pubDate>Sun, 30 Aug 2020 17:54:08 GMT</pubDate>
            <category>nngn</category>
            <category>programming</category>
            <description>Back in 2018, I publicized a project I had been working on intently for more than a year.  Because of the circumstances, it ended up never having its own entry here in this blog.  That is finally being corrected, and I am going to write not just one, but a series of posts about it.</description>
        </item>
        <item>
            <title>SIGFPE</title>
            <link>https://bbguimaraes.com/blog/sigfpe.html</link>
            <guid>https://bbguimaraes.com/blog/sigfpe.html</guid>
            <pubDate>Wed, 20 May 2020 21:56:52 GMT</pubDate>
            <category>assembly</category>
            <category>c</category>
            <category>debugging</category>
            <category>linux</category>
            <category>math</category>
            <category>programming</category>
            <category>unix</category>
            <description>Every programmer at one point will encounter the arcane semantics of IEEE-754 floating-point arithmetic.  If for you that point is right now, allow me to list the worst offenders of the principle of least surprise:</description>
        </item>
        <item>
            <title>Dot product as cosine subtraction</title>
            <link>https://bbguimaraes.com/blog/dot-product-as-cosine-subtraction.html</link>
            <guid>https://bbguimaraes.com/blog/dot-product-as-cosine-subtraction.html</guid>
            <pubDate>Sat, 25 Jan 2020 18:04:00 GMT</pubDate>
            <category>math</category>
            <description>The two principal definitions of the dot product have always seemed incoherent to me.  After trying (and failing) to research this many times, a &lt;a href="https://math.stackexchange.com/a/348744"&gt;math.stackexchange.com question&lt;/a&gt; finally gave an explanation that made sense to me.  Here is my interpretation of it — and trust me, if &lt;em&gt;I&lt;/em&gt; can understand a mathematical concept, so can you.</description>
        </item>
        <item>
            <title>mv ~</title>
            <link>https://bbguimaraes.com/blog/mv-home.html</link>
            <guid>https://bbguimaraes.com/blog/mv-home.html</guid>
            <pubDate>Sun, 21 Jul 2019 21:26:13 GMT</pubDate>
            <category>facebook</category>
            <category>google</category>
            <category>meta</category>
            <description>&lt;p&gt;Both from personal experience and from having read all sorts of blogs, I learned that the secret to not having to give excuses for updating a blog in a very infrequent and irregular fashion is to completely ignore the fact that it has been more than a year since the last post (I would say this is an autological self-reference, but that would be paradoxically contradictory).&lt;/p&gt;&lt;p&gt;The big news this time is that from now on, the new home for this blog is:&lt;/p&gt;&lt;blockquote&gt;&lt;a href="https://bbguimaraes.com/blog"&gt;https://bbguimaraes.com/blog&lt;/a&gt;&lt;/blockquote&gt;</description>
        </item>
        <item>
            <title>~/music</title>
            <link>https://bbguimaraes.com/blog/music.html</link>
            <guid>https://bbguimaraes.com/blog/music.html</guid>
            <pubDate>Sun, 12 Mar 2017 21:12:00 GMT</pubDate>
            <category>music</category>
            <description>For too long my musical (if you can call them that) experiments have been scattered all over the internet.  Not anymore!</description>
        </item>
        <item>
            <title>College research projects</title>
            <link>https://bbguimaraes.com/blog/college-research-projects.html</link>
            <guid>https://bbguimaraes.com/blog/college-research-projects.html</guid>
            <pubDate>Sat, 20 Aug 2016 23:47:00 GMT</pubDate>
            <category>dissertation</category>
            <category>programming</category>
            <category>linux</category>
            <category>math</category>
            <description>A long time ago, when I was in college, I got involved in two research projects.</description>
        </item>
        <item>
            <title>2014 books</title>
            <link>https://bbguimaraes.com/blog/2014-books.html</link>
            <guid>https://bbguimaraes.com/blog/2014-books.html</guid>
            <pubDate>Tue, 20 Jan 2015 16:42:00 GMT</pubDate>
            <category>c</category>
            <category>vim</category>
            <category>tdd</category>
            <category>oreilly</category>
            <category>tmux</category>
            <category>programming</category>
            <category>linux</category>
            <category>apache</category>
            <category>books</category>
            <category>unix</category>
            <category>shell</category>
            <category>sicp</category>
            <description>I read a lot of books.  Last year I had some money laying around and decided to put it to good use.  I ended up buying fourteen books from O'Reilly (simply the best publisher in the technology field) on May and finally finished reading them all (exception bellow) on the first days of this year.  This a quick and informal review of each of them.</description>
        </item>
        <item>
            <title>Calculating π the unix way</title>
            <link>https://bbguimaraes.com/blog/calculating-pi-the-unix-way.html</link>
            <guid>https://bbguimaraes.com/blog/calculating-pi-the-unix-way.html</guid>
            <pubDate>Thu, 11 Dec 2014 22:51:00 GMT</pubDate>
            <category>printf</category>
            <category>head</category>
            <category>python</category>
            <category>pi</category>
            <category>bash</category>
            <category>bc</category>
            <category>math</category>
            <category>grep</category>
            <category>whatis</category>
            <category>man</category>
            <category>pipe</category>
            <category>paste</category>
            <category>seq</category>
            <category>unix</category>
            <category>shell</category>
            <description>A nice trick I learned a while ago that is worth sharing: calculating pi the unix way (you know, on the command line, with pipes, as god intended).</description>
        </item>
        <item>
            <title>pip --extra-index</title>
            <link>https://bbguimaraes.com/blog/pip-extra-index.html</link>
            <guid>https://bbguimaraes.com/blog/pip-extra-index.html</guid>
            <pubDate>Wed, 10 Dec 2014 12:46:00 GMT</pubDate>
            <category>pip</category>
            <category>lsof</category>
            <category>webserver</category>
            <category>debugging</category>
            <category>python</category>
            <category>socket</category>
            <category>strace</category>
            <category>grep</category>
            <category>programming</category>
            <category>linux</category>
            <category>man</category>
            <category>unix</category>
            <description>This is a tale of debugging.  That fine art of digging the darkest corners of a computer system to solve whatever problem is haunting it.  This particular story is about python's package manager, pip.</description>
        </item>
        <item>
            <title>Manufacturer's blues</title>
            <link>https://bbguimaraes.com/blog/manufacturers-blues.html</link>
            <guid>https://bbguimaraes.com/blog/manufacturers-blues.html</guid>
            <pubDate>Fri, 02 May 2014 16:13:00 GMT</pubDate>
            <category>mp3</category>
            <category>badvoltage</category>
            <category>dos</category>
            <category>arch</category>
            <category>pacman</category>
            <category>shell</category>
            <category>linux</category>
            <category>billy</category>
            <category>filesystem</category>
            <category>mkfs</category>
            <category>fat</category>
            <category>unix</category>
            <description>The state of technology sometimes gives me the blues.</description>
        </item>
        <item>
            <title>Uploading files the unix way</title>
            <link>https://bbguimaraes.com/blog/uploading-files-the-unix-way.html</link>
            <guid>https://bbguimaraes.com/blog/uploading-files-the-unix-way.html</guid>
            <pubDate>Tue, 04 Mar 2014 00:26:00 GMT</pubDate>
            <category>cowsay</category>
            <category>potato souffle</category>
            <category>webserver</category>
            <category>perl</category>
            <category>nsa</category>
            <category>vim</category>
            <category>raspberry pi</category>
            <category>ssh</category>
            <category>shell</category>
            <category>netcat</category>
            <category>less</category>
            <category>man</category>
            <category>debian</category>
            <category>dropbox</category>
            <category>unix</category>
            <category>gedit</category>
            <description>I just did something which I thought was worth sharing.  It shows a couple of fundamental techniques in unix systems used in a context where most people would not think of.</description>
        </item>
        <item>
            <title>A post-mortem</title>
            <link>https://bbguimaraes.com/blog/a-post-mortem.html</link>
            <guid>https://bbguimaraes.com/blog/a-post-mortem.html</guid>
            <pubDate>Sun, 14 Jul 2013 22:14:00 GMT</pubDate>
            <category>programming</category>
            <category>raspbian</category>
            <category>linux</category>
            <category>arch</category>
            <category>raspberry pi</category>
            <description>&lt;a href="https://bbguimaraes.com/blog/that-moment-you-realize-something-really-wrong-is-going-on.html" target="_blank"&gt;A lot&lt;/a&gt; has happened since &lt;a href="https://bbguimaraes.com/blog/the-raspberry.html" target="_blank"&gt;my first rπ post&lt;/a&gt;.</description>
        </item>
        <item>
            <title>That moment you realize something really wrong is going on</title>
            <link>https://bbguimaraes.com/blog/that-moment-you-realize-something-really-wrong-is-going-on.html</link>
            <guid>https://bbguimaraes.com/blog/that-moment-you-realize-something-really-wrong-is-going-on.html</guid>
            <pubDate>Thu, 30 May 2013 22:18:00 GMT</pubDate>
            <category>dpkg</category>
            <category>apt-get</category>
            <category>shell</category>
            <category>linux</category>
            <category>raspberry pi</category>
            <description />
        </item>
        <item>
            <title>Python mocking</title>
            <link>https://bbguimaraes.com/blog/python-mocking.html</link>
            <guid>https://bbguimaraes.com/blog/python-mocking.html</guid>
            <pubDate>Sat, 11 May 2013 19:17:00 GMT</pubDate>
            <category>best practices</category>
            <category>programming</category>
            <category>python</category>
            <category>coding style</category>
            <category>mock</category>
            <description>If you are into unit testing, you probably have been introduced to mocking. And if that is the case, you probably already have been bitten by it. Mocking requires some understanding of code execution, importing and name resolution that most people lack when first encountering such situations. In Python, mocking is a relatively simple process, if you analyze carefully what needs to be done.</description>
        </item>
        <item>
            <title>Handy bash substitution</title>
            <link>https://bbguimaraes.com/blog/handy-bash-substitution.html</link>
            <guid>https://bbguimaraes.com/blog/handy-bash-substitution.html</guid>
            <pubDate>Sun, 24 Feb 2013 04:06:00 GMT</pubDate>
            <category>tar</category>
            <category>awk</category>
            <category>jethro tull</category>
            <category>perl</category>
            <category>wget</category>
            <category>find</category>
            <category>bash substitution</category>
            <category>bash expansion</category>
            <category>shell</category>
            <category>programming</category>
            <category>linux</category>
            <category>du</category>
            <description>Working on the command line is awesome. But there are times where all the typing gets unwieldy. No one likes to type a long file name a lot of times. Sure, using the up arrow and tab keys can make things faster sometimes, but I'll show you some tricks to make your life easier.</description>
        </item>
        <item>
            <title>An image is worth a thousand megabytes</title>
            <link>https://bbguimaraes.com/blog/an-image-is-worth-a-thousand-megabytes.html</link>
            <guid>https://bbguimaraes.com/blog/an-image-is-worth-a-thousand-megabytes.html</guid>
            <pubDate>Thu, 07 Feb 2013 01:11:00 GMT</pubDate>
            <category>df</category>
            <category>sha1sum</category>
            <category>raspbian</category>
            <category>linux</category>
            <category>dd</category>
            <category>wget</category>
            <category>raspberry pi</category>
            <description>Now we have all the components we need to run our Raspberry Pi, we can start preparing them to actually work together.</description>
        </item>
        <item>
            <title>The raspberry</title>
            <link>https://bbguimaraes.com/blog/the-raspberry.html</link>
            <guid>https://bbguimaraes.com/blog/the-raspberry.html</guid>
            <pubDate>Wed, 23 Jan 2013 23:29:00 GMT</pubDate>
            <category>raspbian</category>
            <category>linux</category>
            <category>raspberry pi</category>
            <description>My late Christmas gift (from me to myself) arrived on Monday, and it is a little Raspberry Pi.</description>
        </item>
        <item>
            <title>The super user is more powerful than god</title>
            <link>https://bbguimaraes.com/blog/the-super-user-is-more-powerful-than-god.html</link>
            <guid>https://bbguimaraes.com/blog/the-super-user-is-more-powerful-than-god.html</guid>
            <pubDate>Fri, 21 Dec 2012 10:48:00 GMT</pubDate>
            <category>shell</category>
            <category>linux</category>
            <description />
        </item>
        <item>
            <title>Hiding text in LaTeX</title>
            <link>https://bbguimaraes.com/blog/hiding-text-in-latex.html</link>
            <guid>https://bbguimaraes.com/blog/hiding-text-in-latex.html</guid>
            <pubDate>Sun, 04 Nov 2012 22:24:00 GMT</pubDate>
            <category>dissertation</category>
            <category>latex</category>
            <description>When writing my dissertation, I like to leave some text that I won't use at that particular moment but know I will need in the (near) future.</description>
        </item>
        <item>
            <title>Problem when adding SSH key on github</title>
            <link>https://bbguimaraes.com/blog/problem-when-adding-ssh-key-on-github.html</link>
            <guid>https://bbguimaraes.com/blog/problem-when-adding-ssh-key-on-github.html</guid>
            <pubDate>Sun, 28 Oct 2012 03:41:00 GMT</pubDate>
            <category>curl</category>
            <category>git</category>
            <category>github</category>
            <description>Recently, I had I problem with github. I couldn't add SSH keys anymore, the web page would just hang and present me a "Connection reset" error after a few (annoying) minutes. I struggled for a week, but have finally found a solution, which is not the best, but at least I can access github from my machine once again.</description>
        </item>
        <item>
            <title>perl is beautiful - part 3</title>
            <link>https://bbguimaraes.com/blog/perl-is-beautiful3.html</link>
            <guid>https://bbguimaraes.com/blog/perl-is-beautiful3.html</guid>
            <pubDate>Tue, 23 Oct 2012 01:25:00 GMT</pubDate>
            <category>programming</category>
            <category>perl</category>
            <description>In the last post on the subject, I'll show a couple more perl tricks I use everyday.</description>
        </item>
        <item>
            <title>Low-level language</title>
            <link>https://bbguimaraes.com/blog/low-level-language.html</link>
            <guid>https://bbguimaraes.com/blog/low-level-language.html</guid>
            <pubDate>Mon, 22 Oct 2012 03:01:00 GMT</pubDate>
            <category>portuguese</category>
            <category>language</category>
            <description>"Tudo é céu, tudo é mar; torvo negrume sobre as cabeças borrascoso pesa, e horrenda espessa treva enoita as ondas." MARÃO, Públio Virgílio. &lt;i&gt;Eneida&lt;/i&gt;.</description>
        </item>
        <item>
            <title>perl is beautiful - part 2</title>
            <link>https://bbguimaraes.com/blog/perl-is-beautiful2.html</link>
            <guid>https://bbguimaraes.com/blog/perl-is-beautiful2.html</guid>
            <pubDate>Thu, 18 Oct 2012 10:53:00 GMT</pubDate>
            <category>programming</category>
            <category>perl</category>
            <description>We've seen how perl can be used, but you may be wondering, so what? Fasten your seatbelt, for fun begins now.</description>
        </item>
        <item>
            <title>perl is beautiful</title>
            <link>https://bbguimaraes.com/blog/perl-is-beautiful.html</link>
            <guid>https://bbguimaraes.com/blog/perl-is-beautiful.html</guid>
            <pubDate>Tue, 02 Oct 2012 02:18:00 GMT</pubDate>
            <category>programming</category>
            <category>perl</category>
            <description>Writing the first post on a blog about programming is fairly easy. Now, the second one needed a little thought to come up with. I decided to show a trick I use almost daily, be it at work or on personal projects.</description>
        </item>
        <item>
            <title>99 Bottles of Beer</title>
            <link>https://bbguimaraes.com/blog/99-bottles-of-beer.html</link>
            <guid>https://bbguimaraes.com/blog/99-bottles-of-beer.html</guid>
            <pubDate>Mon, 01 Oct 2012 03:13:00 GMT</pubDate>
            <category>programming</category>
            <category>hello world</category>
            <category>assembly</category>
            <category>vim</category>
            <description />
        </item>
    </channel>
</rss>
